### ISSUE TITLE
Feature Request: Use GoogleCredential.getApplicationDefault

### ISSUE THREAD

**Issue by dmitrii-stebliuk** [potix2/spark-google-spreadsheets#16]
The current authentication way:
```
val credential = new Builder()
          .setTransport(HTTP_TRANSPORT)
          .setJsonFactory(JSON_FACTORY)
          .setServiceAccountId(serviceAccountId)
          .setServiceAccountPrivateKeyFromP12File(p12File)
          .setServiceAccountScopes(scopes)
          .build()
```
requires to specify a service account and path to the credential's file:
```
final val DEFAULT_CREDENTIAL_PATH = "/etc/gdata/credential.p12"
val credentialPath = parameters.getOrElse("credentialPath", DEFAULT_CREDENTIAL_PATH)
SparkSpreadsheetService(serviceAccountId, new File(credentialPath))
```
Using `new File(..)` does not allow to put the credentials into jar, it's better to use `getResourceAsStream` to support jars.
Also a simpler authentication approach would be to use `GoogleCredential.getApplicationDefault` that depends on the `GOOGLE_APPLICATION_CREDENTIALS` environment variable in the path that is set inside Google Cloud: https://developers.google.com/api-client-library/java/google-api-java-client/reference/1.19.1/com/google/api/client/googleapis/auth/oauth2/GoogleCredential#getApplicationDefault()

Let's implement a fallback scenario that if there is no service account id specified then just use `GoogleCredential.getApplicationDefault` instead of raising exception.

**Comment by potix2** [comment]
Since your pull request was merged, this issue is closed. Thank you a lot.
