### ISSUE TITLE
enforcing Integer type 

### ISSUE THREAD

**Issue by Bertrandbenj** [potix2/spark-google-spreadsheets#2]
How do you enforce Integer/float type?
- it infer as string every fields and if I don t give it a schema. 
- It breaks at parsing if I give a schema with IntegerType.

I went into GSpreadsheet and try to enforce the column type to "0" which is the closest to an integer representation. It didnt help. 

Do you have a working example to start with ? 

to reproduce the Issue with your example (in java - assuming there is no difference in the execution just a syntax) : 

```
 DataFrame test = sqlContext.read()
        .format("com.github.potix2.spark.google.spreadsheets")
        .option("serviceAccountId", "53797494708-ds5v22b6cbpchrv2qih1vg8kru098k9i@developer.gserviceaccount.com")
        .option("credentialPath", "res/spark-google-spreadsheets-test-eb7b191d1e1d.p12")
        .load("SpreadsheetSuite/case1")
        .cache();
```

output 

> root
>  |-- col3: string (nullable = true)
>  |-- col2: string (nullable = true)
>  |-- col1: string (nullable = true)
> 
> +----+----+----+
> |col3|col2|col1|
> +----+----+----+
> |   3|   2|   1|
> |   4|   3|   2|
> |   5|   4|   3|

but when forcing the schema  like : 

```
        final StructType sttest= new StructType(new StructField[] {
                new StructField("col1",DataTypes.IntegerType,true,Metadata.empty()),
                new StructField("col2",DataTypes.StringType,true, Metadata.empty()), 
                new StructField("col3",DataTypes.StringType,true, Metadata.empty()),
        });

        DataFrame test = sqlContext.read()
        .format("com.github.potix2.spark.google.spreadsheets")
        .option("serviceAccountId", "53797494708-ds5v22b6cbpchrv2qih1vg8kru098k9i@developer.gserviceaccount.com")
        .option("credentialPath", "res/spark-google-spreadsheets-test-eb7b191d1e1d.p12")
        .schema(sttest)
        .load("SpreadsheetSuite/case1")
        .cache();

        test.printSchema();
        test.show();
```

The execution of show() fails to cast integer to string 

> java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
>   at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:101)

So is it because : 
- we can only get the data as string ?
- Because of the column header parsing?  (I tried on a custom spreadsheet without headers but it didnt work )
- a feature to be added later ? 
- Some java/scala issue ? 

Any advice is appreciated 
but that would be a cool module for me to use

**Comment by potix2** [comment]
@Bertrandbenj Thank you for reporting a issue.

> we can only get the data as string ?

You're right. It's defect. I try to fix this issue quickly. 
Thanks!

**Comment by potix2** [comment]
This issue is fixed at https://github.com/potix2/spark-google-spreadsheets/commit/1a8c80fc7f24b19478995bdb4b458eb9b65b5824 .
