### ISSUE TITLE
Ignores column value save, if the column name has underscore in it.

### ISSUE THREAD

**Issue by pradeepmantha** [potix2/spark-google-spreadsheets#3]

**Comment by potix2** [comment]
This issue is caused by the limitation of Google Sheets API v3. To fix some issues included this one I'll migrate to Google Sheets API v4 in the next release.

**Comment by potix2** [comment]
@pradeepmantha This issues was fixed at [0.4.0](https://github.com/potix2/spark-google-spreadsheets/releases/tag/0.4.0)
