### ISSUE TITLE
No support for Spark 2.0, write document fails

### ISSUE THREAD

**Issue by Henningdev** [potix2/spark-google-spreadsheets#5]
Hi, 

The basic example with read from google sheets and write back fails with a stacktrace when running on Spark 2.0;

val df = sqlContext.read.format("com.github.potix2.spark.google.spreadsheets").
    option("serviceAccountId", accountId).
    option("credentialPath", credPath).
    load(SPREADSHEET_ID+"/"+SPREADSHEET_NAME) 

df: org.apache.spark.sql.DataFrame = [TEST : string, TEST2: string]
scala> df.show
+-----+-----+
|TEST |TEST2|
+-----+-----+
|    a    |    b   |
|    c    |    d   |
+-----+-----+

scala> df.write.format("com.github.potix2.spark.google.spreadsheets").
    option("serviceAccountId", accountId).
    option("credentialPath", credPath).
    save(SPREADSHEET_ID+"/"+SPREADSHEET_NAME+"_new")

java.lang.AbstractMethodError: com.github.potix2.spark.google.spreadsheets.DefaultSource.createRelation(Lorg/apache/spark/sql/SQLContext;Lorg/apache/spark/sql/SaveMode;Lscala/collection/immutable/Map;Lorg/apache/spark/sql/Dataset;)Lorg/apache/spark/sql/sources/BaseRelation;
  at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:442)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:211)
  at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:194)
  ... 48 elided

**Comment by Henningdev** [comment]
Must be a class version error.. I was running Spark 2.0.2 when spark-google-spreadsheets lib is compiled with Spark-core 1.6.2. Do you plan to release a new build for 2.0 series Spark?

**Comment by potix2** [comment]
@Henningdev Thank you for reporting. I am planning to support spark 2.0 and there is a development branch locally. I will do my best to be released as soon as possible.

**Comment by Henningdev** [comment]
@potix2 Superb! Google Sheets and Spark is a nice combo when analysing and presenting data

**Comment by potix2** [comment]
Now, version 0.5.0 for Spark 2.0.x is released!
